name: my-docker-project

services:
  app:
    image: my-docker-image
    container_name: my-docker-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - .:/app
